/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    NewDevelopmentalStage,
    NewDevelopmentalStageFromJSON,
    NewDevelopmentalStageToJSON,
} from '../models';

export interface DevelopmentalStagesGetRequest {
    limit?: number;
    sort?: string;
    start?: number;
    eq?: string;
    ne?: string;
    lt?: string;
    lte?: string;
    gt?: string;
    gte?: string;
    contains?: string;
    containss?: string;
    _in?: Array<string>;
    nin?: Array<string>;
}

export interface DevelopmentalStagesIdDeleteRequest {
    id: string;
}

export interface DevelopmentalStagesIdGetRequest {
    id: string;
}

export interface DevelopmentalStagesIdPutRequest {
    id: string;
    newDevelopmentalStage: NewDevelopmentalStage;
}

export interface DevelopmentalStagesPostRequest {
    newDevelopmentalStage: NewDevelopmentalStage;
}

/**
 * 
 */
export class DevelopmentalStageApi extends runtime.BaseAPI {

    /**
     */
    async developmentalStagesCountGetRaw(): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/developmental-stages/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async developmentalStagesCountGet(): Promise<object> {
        const response = await this.developmentalStagesCountGetRaw();
        return await response.value();
    }

    /**
     */
    async developmentalStagesGetRaw(requestParameters: DevelopmentalStagesGetRequest): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['_start'] = requestParameters.start;
        }

        if (requestParameters.eq !== undefined) {
            queryParameters['_eq'] = requestParameters.eq;
        }

        if (requestParameters.ne !== undefined) {
            queryParameters['_ne'] = requestParameters.ne;
        }

        if (requestParameters.lt !== undefined) {
            queryParameters['_lt'] = requestParameters.lt;
        }

        if (requestParameters.lte !== undefined) {
            queryParameters['_lte'] = requestParameters.lte;
        }

        if (requestParameters.gt !== undefined) {
            queryParameters['_gt'] = requestParameters.gt;
        }

        if (requestParameters.gte !== undefined) {
            queryParameters['_gte'] = requestParameters.gte;
        }

        if (requestParameters.contains !== undefined) {
            queryParameters['_contains'] = requestParameters.contains;
        }

        if (requestParameters.containss !== undefined) {
            queryParameters['_containss'] = requestParameters.containss;
        }

        if (requestParameters._in) {
            queryParameters['_in'] = requestParameters._in;
        }

        if (requestParameters.nin) {
            queryParameters['_nin'] = requestParameters.nin;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/developmental-stages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async developmentalStagesGet(requestParameters: DevelopmentalStagesGetRequest): Promise<object> {
        const response = await this.developmentalStagesGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete a record
     */
    async developmentalStagesIdDeleteRaw(requestParameters: DevelopmentalStagesIdDeleteRequest): Promise<runtime.ApiResponse<number>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling developmentalStagesIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/developmental-stages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Delete a record
     */
    async developmentalStagesIdDelete(requestParameters: DevelopmentalStagesIdDeleteRequest): Promise<number> {
        const response = await this.developmentalStagesIdDeleteRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async developmentalStagesIdGetRaw(requestParameters: DevelopmentalStagesIdGetRequest): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling developmentalStagesIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/developmental-stages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async developmentalStagesIdGet(requestParameters: DevelopmentalStagesIdGetRequest): Promise<object> {
        const response = await this.developmentalStagesIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update a record
     */
    async developmentalStagesIdPutRaw(requestParameters: DevelopmentalStagesIdPutRequest): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling developmentalStagesIdPut.');
        }

        if (requestParameters.newDevelopmentalStage === null || requestParameters.newDevelopmentalStage === undefined) {
            throw new runtime.RequiredError('newDevelopmentalStage','Required parameter requestParameters.newDevelopmentalStage was null or undefined when calling developmentalStagesIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/developmental-stages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewDevelopmentalStageToJSON(requestParameters.newDevelopmentalStage),
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update a record
     */
    async developmentalStagesIdPut(requestParameters: DevelopmentalStagesIdPutRequest): Promise<object> {
        const response = await this.developmentalStagesIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create a new record
     */
    async developmentalStagesPostRaw(requestParameters: DevelopmentalStagesPostRequest): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.newDevelopmentalStage === null || requestParameters.newDevelopmentalStage === undefined) {
            throw new runtime.RequiredError('newDevelopmentalStage','Required parameter requestParameters.newDevelopmentalStage was null or undefined when calling developmentalStagesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/developmental-stages`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewDevelopmentalStageToJSON(requestParameters.newDevelopmentalStage),
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a new record
     */
    async developmentalStagesPost(requestParameters: DevelopmentalStagesPostRequest): Promise<object> {
        const response = await this.developmentalStagesPostRaw(requestParameters);
        return await response.value();
    }

}
