/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    NewSynapse,
    NewSynapseFromJSON,
    NewSynapseToJSON,
    Synapse,
    SynapseFromJSON,
    SynapseToJSON,
} from '../models';

export interface SynapsesGetRequest {
    limit?: number;
    sort?: string;
    start?: number;
    eq?: string;
    ne?: string;
    lt?: string;
    lte?: string;
    gt?: string;
    gte?: string;
    contains?: string;
    containss?: string;
    _in?: Array<string>;
    nin?: Array<string>;
}

export interface SynapsesIdDeleteRequest {
    id: string;
}

export interface SynapsesIdGetRequest {
    id: string;
}

export interface SynapsesIdPutRequest {
    id: string;
    newSynapse: NewSynapse;
}

export interface SynapsesPostRequest {
    newSynapse: NewSynapse;
}

/**
 * 
 */
export class SynapseApi extends runtime.BaseAPI {

    /**
     */
    async synapsesCountGetRaw(): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/synapses/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async synapsesCountGet(): Promise<object> {
        const response = await this.synapsesCountGetRaw();
        return await response.value();
    }

    /**
     */
    async synapsesGetRaw(requestParameters: SynapsesGetRequest): Promise<runtime.ApiResponse<Array<Synapse>>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['_start'] = requestParameters.start;
        }

        if (requestParameters.eq !== undefined) {
            queryParameters['_eq'] = requestParameters.eq;
        }

        if (requestParameters.ne !== undefined) {
            queryParameters['_ne'] = requestParameters.ne;
        }

        if (requestParameters.lt !== undefined) {
            queryParameters['_lt'] = requestParameters.lt;
        }

        if (requestParameters.lte !== undefined) {
            queryParameters['_lte'] = requestParameters.lte;
        }

        if (requestParameters.gt !== undefined) {
            queryParameters['_gt'] = requestParameters.gt;
        }

        if (requestParameters.gte !== undefined) {
            queryParameters['_gte'] = requestParameters.gte;
        }

        if (requestParameters.contains !== undefined) {
            queryParameters['_contains'] = requestParameters.contains;
        }

        if (requestParameters.containss !== undefined) {
            queryParameters['_containss'] = requestParameters.containss;
        }

        if (requestParameters._in) {
            queryParameters['_in'] = requestParameters._in;
        }

        if (requestParameters.nin) {
            queryParameters['_nin'] = requestParameters.nin;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/synapses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SynapseFromJSON));
    }

    /**
     */
    async synapsesGet(requestParameters: SynapsesGetRequest): Promise<Array<Synapse>> {
        const response = await this.synapsesGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete a record
     */
    async synapsesIdDeleteRaw(requestParameters: SynapsesIdDeleteRequest): Promise<runtime.ApiResponse<number>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling synapsesIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/synapses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Delete a record
     */
    async synapsesIdDelete(requestParameters: SynapsesIdDeleteRequest): Promise<number> {
        const response = await this.synapsesIdDeleteRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async synapsesIdGetRaw(requestParameters: SynapsesIdGetRequest): Promise<runtime.ApiResponse<Synapse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling synapsesIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/synapses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SynapseFromJSON(jsonValue));
    }

    /**
     */
    async synapsesIdGet(requestParameters: SynapsesIdGetRequest): Promise<Synapse> {
        const response = await this.synapsesIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update a record
     */
    async synapsesIdPutRaw(requestParameters: SynapsesIdPutRequest): Promise<runtime.ApiResponse<Synapse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling synapsesIdPut.');
        }

        if (requestParameters.newSynapse === null || requestParameters.newSynapse === undefined) {
            throw new runtime.RequiredError('newSynapse','Required parameter requestParameters.newSynapse was null or undefined when calling synapsesIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/synapses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewSynapseToJSON(requestParameters.newSynapse),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SynapseFromJSON(jsonValue));
    }

    /**
     * Update a record
     */
    async synapsesIdPut(requestParameters: SynapsesIdPutRequest): Promise<Synapse> {
        const response = await this.synapsesIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create a new record
     */
    async synapsesPostRaw(requestParameters: SynapsesPostRequest): Promise<runtime.ApiResponse<Synapse>> {
        if (requestParameters.newSynapse === null || requestParameters.newSynapse === undefined) {
            throw new runtime.RequiredError('newSynapse','Required parameter requestParameters.newSynapse was null or undefined when calling synapsesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/synapses`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewSynapseToJSON(requestParameters.newSynapse),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SynapseFromJSON(jsonValue));
    }

    /**
     * Create a new record
     */
    async synapsesPost(requestParameters: SynapsesPostRequest): Promise<Synapse> {
        const response = await this.synapsesPostRaw(requestParameters);
        return await response.value();
    }

}
