NEUROSCAN_APP = "neuroscan"
PROMOTER_DB_APP = "promoterdb"

GENERAL_ERRORS = "general"

NEURONS_FOLDER = "neurons"
SYNAPSES_FOLDER = "synapses"
CONTACTS_FOLDER = "contacts"
CPHATE = "cphate"

NEUROSCAN_EXPECTED_FOLDERS_IN_TIMEPOINT = [NEURONS_FOLDER, SYNAPSES_FOLDER, CONTACTS_FOLDER, CPHATE]

FILE_PREFIX = 'SVV'

CONTACTS_XLS = 'contacts.xls'
CONTACTS_XLS_NEURON_A_COL = 'Neuron 1'
CONTACTS_XLS_NEURON_B_COL = 'Neuron 2'
CONTACTS_XLS_WEIGHT_COL = 'Weight'

CPHATE_XLS = 'cphate.xls'
CPHATE_REQUIRED_COLUMN = 'Neuron'
CPHATE_ITERATION_COLUMN_PREFIX = 'Iter'

SYNAPSE_PRE_POSITION_TYPE = 'PreSyn'
SYNAPSE_POST_POSITION_TYPE = 'PostSyn'
