NEUROSCAN_APP = "neuroscan"
PROMOTER_DB_APP = "promoterdb"

GENERAL_ERRORS = "general"

NEURONS_FOLDER = "neurons"
SYNAPSES_FOLDER = "synapses"
CONTACTS_FOLDER = "contacts"
CPHATE_FOLDER = "cphate"

NEUROSCAN_EXPECTED_FOLDERS_IN_TIMEPOINT = [NEURONS_FOLDER, SYNAPSES_FOLDER, CONTACTS_FOLDER, CPHATE_FOLDER]

FILE_PREFIX = 'SVV'

CONTACTS_XLS = 'contacts.xls'
CONTACTS_XLS_NEURON_A_COL = 'Neuron 1'
CONTACTS_XLS_NEURON_B_COL = 'Neuron 2'
CONTACTS_XLS_WEIGHT_COL = 'Weight'

CPHATE_XLS = 'cphate.xls'
CPHATE_REQUIRED_COLUMN = 'Neuron'
CPHATE_ITERATION_COLUMN_PREFIX = 'Iter'

SYNAPSE_PRE_POSITION_TYPE = 'PreSyn'
SYNAPSE_POST_POSITION_TYPE = 'PostSyn'

PROMOTER_FOLDER = 'promoters'
PROMOTER_XLS = 'promoters.xls'

PROMOTER_SHEET1 = "Sheet1"
PROMOTER_SHEET1_PROMOTER_COLUMN = "Promoter"
PROMOTER_SHEET1_BEGIN_TIMEPOINT_COLUMN = "Beginning of expression in minutes"
PROMOTER_SHEET1_END_TIMEPOINT_COLUMN = "Termination of expression in minutes"
PROMOTER_SHEET1_NEURONS_COLUMN = "Neurons"
PROMOTER_SHEET1_STRAIN_INFORMATION_COLUMN = "Strain information"
PROMOTER_SHEET1_DETAILED_EXPRESSION_PATTERNS_COLUMN = "Detailed expression patterns"

PROMOTER_SHEET2 = "Cell-ID based on lineaging"
PROMOTER_SHEET2_NEURON_COLUMN = "Neuron"
PROMOTER_SHEET2_LINEAGE_COLUMN = "Lineage"
PROMOTER_SHEET2_NAME_COLUMN = "Name"
PROMOTER_SHEET2_LOCATION_COLUMN = "Location"
PROMOTER_SHEET2_REQUIRED_COLUMNS = [PROMOTER_SHEET2_NEURON_COLUMN, PROMOTER_SHEET2_LINEAGE_COLUMN,
                                    PROMOTER_SHEET2_NAME_COLUMN, PROMOTER_SHEET2_LOCATION_COLUMN]

PROMOTER_FOLDER_PREFIX = "promoter"
PROMOTER_EXPECTED_FILES = ['promoter.avi', 'timeline.svg', 'model.svg', '3d_expression.avi', 'histone_marker.avi']
