/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import NewUsersPermissionsRole from '../model/NewUsersPermissionsRole';
import UsersPermissionsRole from '../model/UsersPermissionsRole';

/**
* UsersPermissionsRole service.
* @module api/UsersPermissionsRoleApi
* @version 1.0.0
*/
export default class UsersPermissionsRoleApi {

    /**
    * Constructs a new UsersPermissionsRoleApi. 
    * @alias module:api/UsersPermissionsRoleApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Retrieve all role documents
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of results possible
     * @param {String} opts.sort Sort according to a specific field.
     * @param {Number} opts.start Skip a specific number of entries (especially useful for pagination)
     * @param {String} opts.eq Get entries that matches exactly your input
     * @param {String} opts.ne Get records that are not equals to something
     * @param {String} opts.lt Get record that are lower than a value
     * @param {String} opts.lte Get records that are lower than or equal to a value
     * @param {String} opts.gt Get records that are greater than a value
     * @param {String} opts.gte Get records that are greater than  or equal a value
     * @param {String} opts.contains Get records that contains a value
     * @param {String} opts.containss Get records that contains (case sensitive) a value
     * @param {Array.<String>} opts._in Get records that matches any value in the array of values
     * @param {Array.<String>} opts.nin Get records that doesn't match any value in the array of values
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UsersPermissionsRole>} and HTTP response
     */
    usersPermissionsRolesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        '_limit': opts['limit'],
        '_sort': opts['sort'],
        '_start': opts['start'],
        '_eq': opts['eq'],
        '_ne': opts['ne'],
        '_lt': opts['lt'],
        '_lte': opts['lte'],
        '_gt': opts['gt'],
        '_gte': opts['gte'],
        '_contains': opts['contains'],
        '_containss': opts['containss'],
        '_in': this.apiClient.buildCollectionParam(opts['_in'], 'multi'),
        '_nin': this.apiClient.buildCollectionParam(opts['nin'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UsersPermissionsRole];
      return this.apiClient.callApi(
        '/users-permissions/roles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve all role documents
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of results possible
     * @param {String} opts.sort Sort according to a specific field.
     * @param {Number} opts.start Skip a specific number of entries (especially useful for pagination)
     * @param {String} opts.eq Get entries that matches exactly your input
     * @param {String} opts.ne Get records that are not equals to something
     * @param {String} opts.lt Get record that are lower than a value
     * @param {String} opts.lte Get records that are lower than or equal to a value
     * @param {String} opts.gt Get records that are greater than a value
     * @param {String} opts.gte Get records that are greater than  or equal a value
     * @param {String} opts.contains Get records that contains a value
     * @param {String} opts.containss Get records that contains (case sensitive) a value
     * @param {Array.<String>} opts._in Get records that matches any value in the array of values
     * @param {Array.<String>} opts.nin Get records that doesn't match any value in the array of values
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UsersPermissionsRole>}
     */
    usersPermissionsRolesGet(opts) {
      return this.usersPermissionsRolesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve a role depending on its id
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UsersPermissionsRole} and HTTP response
     */
    usersPermissionsRolesIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling usersPermissionsRolesIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UsersPermissionsRole;
      return this.apiClient.callApi(
        '/users-permissions/roles/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve a role depending on its id
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UsersPermissionsRole}
     */
    usersPermissionsRolesIdGet(id) {
      return this.usersPermissionsRolesIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a new role
     * @param {module:model/NewUsersPermissionsRole} newUsersPermissionsRole 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UsersPermissionsRole} and HTTP response
     */
    usersPermissionsRolesPostWithHttpInfo(newUsersPermissionsRole) {
      let postBody = newUsersPermissionsRole;
      // verify the required parameter 'newUsersPermissionsRole' is set
      if (newUsersPermissionsRole === undefined || newUsersPermissionsRole === null) {
        throw new Error("Missing the required parameter 'newUsersPermissionsRole' when calling usersPermissionsRolesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UsersPermissionsRole;
      return this.apiClient.callApi(
        '/users-permissions/roles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a new role
     * @param {module:model/NewUsersPermissionsRole} newUsersPermissionsRole 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UsersPermissionsRole}
     */
    usersPermissionsRolesPost(newUsersPermissionsRole) {
      return this.usersPermissionsRolesPostWithHttpInfo(newUsersPermissionsRole)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a role
     * @param {String} role 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    usersPermissionsRolesRoleDeleteWithHttpInfo(role) {
      let postBody = null;
      // verify the required parameter 'role' is set
      if (role === undefined || role === null) {
        throw new Error("Missing the required parameter 'role' when calling usersPermissionsRolesRoleDelete");
      }

      let pathParams = {
        'role': role
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/users-permissions/roles/{role}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a role
     * @param {String} role 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    usersPermissionsRolesRoleDelete(role) {
      return this.usersPermissionsRolesRoleDeleteWithHttpInfo(role)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a role
     * @param {String} role 
     * @param {module:model/NewUsersPermissionsRole} newUsersPermissionsRole 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UsersPermissionsRole} and HTTP response
     */
    usersPermissionsRolesRolePutWithHttpInfo(role, newUsersPermissionsRole) {
      let postBody = newUsersPermissionsRole;
      // verify the required parameter 'role' is set
      if (role === undefined || role === null) {
        throw new Error("Missing the required parameter 'role' when calling usersPermissionsRolesRolePut");
      }
      // verify the required parameter 'newUsersPermissionsRole' is set
      if (newUsersPermissionsRole === undefined || newUsersPermissionsRole === null) {
        throw new Error("Missing the required parameter 'newUsersPermissionsRole' when calling usersPermissionsRolesRolePut");
      }

      let pathParams = {
        'role': role
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UsersPermissionsRole;
      return this.apiClient.callApi(
        '/users-permissions/roles/{role}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update a role
     * @param {String} role 
     * @param {module:model/NewUsersPermissionsRole} newUsersPermissionsRole 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UsersPermissionsRole}
     */
    usersPermissionsRolesRolePut(role, newUsersPermissionsRole) {
      return this.usersPermissionsRolesRolePutWithHttpInfo(role, newUsersPermissionsRole)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
