/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Neuron,
    NeuronFromJSON,
    NeuronFromJSONTyped,
    NeuronToJSON,
} from './';

/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    name?: string;
    /**
     * 
     * @type {Neuron}
     * @memberof Contact
     */
    neuronA?: Neuron;
    /**
     * 
     * @type {Neuron}
     * @memberof Contact
     */
    neuronB?: Neuron;
    /**
     * 
     * @type {Array<object>}
     * @memberof Contact
     */
    files?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    metadata?: string;
    /**
     * 
     * @type {Date}
     * @memberof Contact
     */
    publishedAt?: Date;
}

export function ContactFromJSON(json: any): Contact {
    return ContactFromJSONTyped(json, false);
}

export function ContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'neuronA': !exists(json, 'neuronA') ? undefined : NeuronFromJSON(json['neuronA']),
        'neuronB': !exists(json, 'neuronB') ? undefined : NeuronFromJSON(json['neuronB']),
        'files': !exists(json, 'files') ? undefined : json['files'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
    };
}

export function ContactToJSON(value?: Contact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'neuronA': NeuronToJSON(value.neuronA),
        'neuronB': NeuronToJSON(value.neuronB),
        'files': value.files,
        'metadata': value.metadata,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
    };
}


