/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DevelopmentalStage
 */
export interface DevelopmentalStage {
    /**
     * 
     * @type {string}
     * @memberof DevelopmentalStage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DevelopmentalStage
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof DevelopmentalStage
     */
    publishedAt?: Date;
}

export function DevelopmentalStageFromJSON(json: any): DevelopmentalStage {
    return DevelopmentalStageFromJSONTyped(json, false);
}

export function DevelopmentalStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevelopmentalStage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
    };
}

export function DevelopmentalStageToJSON(value?: DevelopmentalStage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
    };
}


