/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailConfirmationForm
 */
export interface EmailConfirmationForm {
    /**
     * 
     * @type {string}
     * @memberof EmailConfirmationForm
     */
    email: string;
}

export function EmailConfirmationFormFromJSON(json: any): EmailConfirmationForm {
    return EmailConfirmationFormFromJSONTyped(json, false);
}

export function EmailConfirmationFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailConfirmationForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EmailConfirmationFormToJSON(value?: EmailConfirmationForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}


