/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalAuthForm
 */
export interface LocalAuthForm {
    /**
     * 
     * @type {string}
     * @memberof LocalAuthForm
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof LocalAuthForm
     */
    password: string;
}

export function LocalAuthFormFromJSON(json: any): LocalAuthForm {
    return LocalAuthFormFromJSONTyped(json, false);
}

export function LocalAuthFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalAuthForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'password': json['password'],
    };
}

export function LocalAuthFormToJSON(value?: LocalAuthForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'password': value.password,
    };
}


