/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Neuron
 */
export interface Neuron {
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    name?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof Neuron
     */
    files?: Array<object>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Neuron
     */
    developmentalStages?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    metadata?: string;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    wormatlas?: string;
    /**
     * 
     * @type {Date}
     * @memberof Neuron
     */
    publishedAt?: Date;
}

export function NeuronFromJSON(json: any): Neuron {
    return NeuronFromJSONTyped(json, false);
}

export function NeuronFromJSONTyped(json: any, ignoreDiscriminator: boolean): Neuron {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'files': !exists(json, 'files') ? undefined : json['files'],
        'developmentalStages': !exists(json, 'developmental_stages') ? undefined : json['developmental_stages'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'wormatlas': !exists(json, 'wormatlas') ? undefined : json['wormatlas'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
    };
}

export function NeuronToJSON(value?: Neuron | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'files': value.files,
        'developmental_stages': value.developmentalStages,
        'metadata': value.metadata,
        'wormatlas': value.wormatlas,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
    };
}


