/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Promoter,
    PromoterFromJSON,
    PromoterFromJSONTyped,
    PromoterToJSON,
    Synapse,
    SynapseFromJSON,
    SynapseFromJSONTyped,
    SynapseToJSON,
} from './';

/**
 * 
 * @export
 * @interface Neuron
 */
export interface Neuron {
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    file?: string;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    metadata?: string;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    wormatlas?: string;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    uid: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Neuron
     */
    timepoints?: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof Neuron
     */
    embryonic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    lineage?: string;
    /**
     * 
     * @type {string}
     * @memberof Neuron
     */
    location?: string;
    /**
     * 
     * @type {Synapse}
     * @memberof Neuron
     */
    synapse?: Synapse;
    /**
     * 
     * @type {Promoter}
     * @memberof Neuron
     */
    promoter?: Promoter;
    /**
     * 
     * @type {Date}
     * @memberof Neuron
     */
    publishedAt?: Date;
}

export function NeuronFromJSON(json: any): Neuron {
    return NeuronFromJSONTyped(json, false);
}

export function NeuronFromJSONTyped(json: any, ignoreDiscriminator: boolean): Neuron {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'file': !exists(json, 'file') ? undefined : json['file'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'wormatlas': !exists(json, 'wormatlas') ? undefined : json['wormatlas'],
        'uid': json['uid'],
        'timepoints': !exists(json, 'timepoints') ? undefined : json['timepoints'],
        'embryonic': !exists(json, 'embryonic') ? undefined : json['embryonic'],
        'lineage': !exists(json, 'lineage') ? undefined : json['lineage'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'synapse': !exists(json, 'synapse') ? undefined : SynapseFromJSON(json['synapse']),
        'promoter': !exists(json, 'promoter') ? undefined : PromoterFromJSON(json['promoter']),
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
    };
}

export function NeuronToJSON(value?: Neuron | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'file': value.file,
        'metadata': value.metadata,
        'wormatlas': value.wormatlas,
        'uid': value.uid,
        'timepoints': value.timepoints,
        'embryonic': value.embryonic,
        'lineage': value.lineage,
        'location': value.location,
        'synapse': SynapseToJSON(value.synapse),
        'promoter': PromoterToJSON(value.promoter),
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
    };
}


