/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewDevelopmentalStage
 */
export interface NewDevelopmentalStage {
    /**
     * 
     * @type {string}
     * @memberof NewDevelopmentalStage
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof NewDevelopmentalStage
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof NewDevelopmentalStage
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewDevelopmentalStage
     */
    updatedBy?: string;
}

export function NewDevelopmentalStageFromJSON(json: any): NewDevelopmentalStage {
    return NewDevelopmentalStageFromJSONTyped(json, false);
}

export function NewDevelopmentalStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewDevelopmentalStage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewDevelopmentalStageToJSON(value?: NewDevelopmentalStage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


