/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewPromoter
 */
export interface NewPromoter {
    /**
     * 
     * @type {string}
     * @memberof NewPromoter
     */
    uid: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewPromoter
     */
    cellsByLineaging?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewPromoter
     */
    metadata?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof NewPromoter
     */
    timepoints?: Array<number>;
    /**
     * 
     * @type {Date}
     * @memberof NewPromoter
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof NewPromoter
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewPromoter
     */
    updatedBy?: string;
}

export function NewPromoterFromJSON(json: any): NewPromoter {
    return NewPromoterFromJSONTyped(json, false);
}

export function NewPromoterFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewPromoter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uid': json['uid'],
        'cellsByLineaging': !exists(json, 'cellsByLineaging') ? undefined : json['cellsByLineaging'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'timepoints': !exists(json, 'timepoints') ? undefined : json['timepoints'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewPromoterToJSON(value?: NewPromoter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uid': value.uid,
        'cellsByLineaging': value.cellsByLineaging,
        'metadata': value.metadata,
        'timepoints': value.timepoints,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


