/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewSynapse
 */
export interface NewSynapse {
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    neuronPre?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewSynapse
     */
    neuronsPost?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    type?: NewSynapseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    uid: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof NewSynapse
     */
    timepoints?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    metadata?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    zs?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    position?: NewSynapsePositionEnum;
    /**
     * 
     * @type {Date}
     * @memberof NewSynapse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSynapse
     */
    updatedBy?: string;
}

/**
* @export
* @enum {string}
*/
export enum NewSynapseTypeEnum {
    Chemical = 'chemical',
    Electrical = 'electrical'
}/**
* @export
* @enum {string}
*/
export enum NewSynapsePositionEnum {
    Pre = 'pre',
    Post = 'post'
}

export function NewSynapseFromJSON(json: any): NewSynapse {
    return NewSynapseFromJSONTyped(json, false);
}

export function NewSynapseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSynapse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'neuronPre': !exists(json, 'neuronPre') ? undefined : json['neuronPre'],
        'neuronsPost': !exists(json, 'neuronsPost') ? undefined : json['neuronsPost'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'uid': json['uid'],
        'timepoints': !exists(json, 'timepoints') ? undefined : json['timepoints'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'section': !exists(json, 'section') ? undefined : json['section'],
        'zs': !exists(json, 'zs') ? undefined : json['zs'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewSynapseToJSON(value?: NewSynapse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'neuronPre': value.neuronPre,
        'neuronsPost': value.neuronsPost,
        'type': value.type,
        'uid': value.uid,
        'timepoints': value.timepoints,
        'metadata': value.metadata,
        'section': value.section,
        'zs': value.zs,
        'position': value.position,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


