/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewUsersPermissionsRole
 */
export interface NewUsersPermissionsRole {
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewUsersPermissionsRole
     */
    permissions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewUsersPermissionsRole
     */
    users?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewUsersPermissionsRole
     */
    updatedBy?: string;
}

export function NewUsersPermissionsRoleFromJSON(json: any): NewUsersPermissionsRole {
    return NewUsersPermissionsRoleFromJSONTyped(json, false);
}

export function NewUsersPermissionsRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewUsersPermissionsRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
        'users': !exists(json, 'users') ? undefined : json['users'],
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewUsersPermissionsRoleToJSON(value?: NewUsersPermissionsRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'permissions': value.permissions,
        'users': value.users,
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


