/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordForm
 */
export interface ResetPasswordForm {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordForm
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordForm
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordForm
     */
    passwordConfirmation: string;
}

export function ResetPasswordFormFromJSON(json: any): ResetPasswordForm {
    return ResetPasswordFormFromJSONTyped(json, false);
}

export function ResetPasswordFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'password': json['password'],
        'passwordConfirmation': json['passwordConfirmation'],
    };
}

export function ResetPasswordFormToJSON(value?: ResetPasswordForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'password': value.password,
        'passwordConfirmation': value.passwordConfirmation,
    };
}


