/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Neuron,
    NeuronFromJSON,
    NeuronFromJSONTyped,
    NeuronToJSON,
} from './';

/**
 * 
 * @export
 * @interface Synapse
 */
export interface Synapse {
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    id: string;
    /**
     * 
     * @type {Neuron}
     * @memberof Synapse
     */
    neuronPre?: Neuron;
    /**
     * 
     * @type {Array<object>}
     * @memberof Synapse
     */
    neuronsPost?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    file?: string;
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    type?: SynapseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    uid: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Synapse
     */
    timepoints?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    metadata?: string;
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    zs?: string;
    /**
     * 
     * @type {string}
     * @memberof Synapse
     */
    position?: SynapsePositionEnum;
    /**
     * 
     * @type {Date}
     * @memberof Synapse
     */
    publishedAt?: Date;
}

/**
* @export
* @enum {string}
*/
export enum SynapseTypeEnum {
    Chemical = 'chemical',
    Electrical = 'electrical'
}/**
* @export
* @enum {string}
*/
export enum SynapsePositionEnum {
    Pre = 'pre',
    Post = 'post'
}

export function SynapseFromJSON(json: any): Synapse {
    return SynapseFromJSONTyped(json, false);
}

export function SynapseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Synapse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'neuronPre': !exists(json, 'neuronPre') ? undefined : NeuronFromJSON(json['neuronPre']),
        'neuronsPost': !exists(json, 'neuronsPost') ? undefined : json['neuronsPost'],
        'file': !exists(json, 'file') ? undefined : json['file'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'uid': json['uid'],
        'timepoints': !exists(json, 'timepoints') ? undefined : json['timepoints'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'section': !exists(json, 'section') ? undefined : json['section'],
        'zs': !exists(json, 'zs') ? undefined : json['zs'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
    };
}

export function SynapseToJSON(value?: Synapse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'neuronPre': NeuronToJSON(value.neuronPre),
        'neuronsPost': value.neuronsPost,
        'file': value.file,
        'type': value.type,
        'uid': value.uid,
        'timepoints': value.timepoints,
        'metadata': value.metadata,
        'section': value.section,
        'zs': value.zs,
        'position': value.position,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
    };
}


