/* tslint:disable */
/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadForm
 */
export interface UploadForm {
    /**
     * 
     * @type {string}
     * @memberof UploadForm
     */
    files: string;
}

export function UploadFormFromJSON(json: any): UploadForm {
    return UploadFormFromJSONTyped(json, false);
}

export function UploadFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'files': json['files'],
    };
}

export function UploadFormToJSON(value?: UploadForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'files': value.files,
    };
}


