/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Neuron from './Neuron';

/**
 * The Contact model module.
 * @module model/Contact
 * @version 1.0.0
 */
class Contact {
    /**
     * Constructs a new <code>Contact</code>.
     * @alias module:model/Contact
     * @param id {String} 
     * @param uid {String} 
     */
    constructor(id, uid) { 
        
        Contact.initialize(this, id, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, uid) { 
        obj['id'] = id;
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>Contact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Contact} obj Optional instance to populate.
     * @return {module:model/Contact} The populated <code>Contact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Contact();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('neuronA')) {
                obj['neuronA'] = Neuron.constructFromObject(data['neuronA']);
            }
            if (data.hasOwnProperty('neuronB')) {
                obj['neuronB'] = Neuron.constructFromObject(data['neuronB']);
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('timepoints')) {
                obj['timepoints'] = ApiClient.convertToType(data['timepoints'], ['Number']);
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Contact.prototype['id'] = undefined;

/**
 * @member {String} uid
 */
Contact.prototype['uid'] = undefined;

/**
 * @member {module:model/Neuron} neuronA
 */
Contact.prototype['neuronA'] = undefined;

/**
 * @member {module:model/Neuron} neuronB
 */
Contact.prototype['neuronB'] = undefined;

/**
 * @member {String} file
 */
Contact.prototype['file'] = undefined;

/**
 * @member {String} metadata
 */
Contact.prototype['metadata'] = undefined;

/**
 * @member {Number} weight
 */
Contact.prototype['weight'] = undefined;

/**
 * @member {Array.<Number>} timepoints
 */
Contact.prototype['timepoints'] = undefined;

/**
 * @member {Date} published_at
 */
Contact.prototype['published_at'] = undefined;






export default Contact;

