/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocalAuthForm model module.
 * @module model/LocalAuthForm
 * @version 1.0.0
 */
class LocalAuthForm {
    /**
     * Constructs a new <code>LocalAuthForm</code>.
     * @alias module:model/LocalAuthForm
     * @param identifier {String} 
     * @param password {String} 
     */
    constructor(identifier, password) { 
        
        LocalAuthForm.initialize(this, identifier, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier, password) { 
        obj['identifier'] = identifier;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>LocalAuthForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocalAuthForm} obj Optional instance to populate.
     * @return {module:model/LocalAuthForm} The populated <code>LocalAuthForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocalAuthForm();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} identifier
 */
LocalAuthForm.prototype['identifier'] = undefined;

/**
 * @member {String} password
 */
LocalAuthForm.prototype['password'] = undefined;






export default LocalAuthForm;

