/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Promoter from './Promoter';
import Synapse from './Synapse';

/**
 * The Neuron model module.
 * @module model/Neuron
 * @version 1.0.0
 */
class Neuron {
    /**
     * Constructs a new <code>Neuron</code>.
     * @alias module:model/Neuron
     * @param id {String} 
     * @param uid {String} 
     */
    constructor(id, uid) { 
        
        Neuron.initialize(this, id, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, uid) { 
        obj['id'] = id;
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>Neuron</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Neuron} obj Optional instance to populate.
     * @return {module:model/Neuron} The populated <code>Neuron</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Neuron();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = data['file']['url'];
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
            }
            if (data.hasOwnProperty('wormatlas')) {
                obj['wormatlas'] = ApiClient.convertToType(data['wormatlas'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('timepoints')) {
                obj['timepoints'] = ApiClient.convertToType(data['timepoints'], ['Number']);
            }
            if (data.hasOwnProperty('embryonic')) {
                obj['embryonic'] = ApiClient.convertToType(data['embryonic'], 'Boolean');
            }
            if (data.hasOwnProperty('lineage')) {
                obj['lineage'] = ApiClient.convertToType(data['lineage'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('synapse')) {
                obj['synapse'] = Synapse.constructFromObject(data['synapse']);
            }
            if (data.hasOwnProperty('promoter')) {
                obj['promoter'] = Promoter.constructFromObject(data['promoter']);
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Neuron.prototype['id'] = undefined;

/**
 * @member {String} file
 */
Neuron.prototype['file'] = undefined;

/**
 * @member {String} metadata
 */
Neuron.prototype['metadata'] = undefined;

/**
 * @member {String} wormatlas
 */
Neuron.prototype['wormatlas'] = undefined;

/**
 * @member {String} uid
 */
Neuron.prototype['uid'] = undefined;

/**
 * @member {Array.<Number>} timepoints
 */
Neuron.prototype['timepoints'] = undefined;

/**
 * @member {Boolean} embryonic
 */
Neuron.prototype['embryonic'] = undefined;

/**
 * @member {String} lineage
 */
Neuron.prototype['lineage'] = undefined;

/**
 * @member {String} location
 */
Neuron.prototype['location'] = undefined;

/**
 * @member {module:model/Synapse} synapse
 */
Neuron.prototype['synapse'] = undefined;

/**
 * @member {module:model/Promoter} promoter
 */
Neuron.prototype['promoter'] = undefined;

/**
 * @member {Date} published_at
 */
Neuron.prototype['published_at'] = undefined;






export default Neuron;

