/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewDevelopmentalStage model module.
 * @module model/NewDevelopmentalStage
 * @version 1.0.0
 */
class NewDevelopmentalStage {
    /**
     * Constructs a new <code>NewDevelopmentalStage</code>.
     * @alias module:model/NewDevelopmentalStage
     * @param uid {String} 
     */
    constructor(uid) { 
        
        NewDevelopmentalStage.initialize(this, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uid) { 
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>NewDevelopmentalStage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewDevelopmentalStage} obj Optional instance to populate.
     * @return {module:model/NewDevelopmentalStage} The populated <code>NewDevelopmentalStage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewDevelopmentalStage();

            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('begin')) {
                obj['begin'] = ApiClient.convertToType(data['begin'], 'Number');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Number');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
            if (data.hasOwnProperty('timepoints')) {
                obj['timepoints'] = ApiClient.convertToType(data['timepoints'], ['Number']);
            }
            if (data.hasOwnProperty('promoterDB')) {
                obj['promoterDB'] = ApiClient.convertToType(data['promoterDB'], 'Boolean');
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('updated_by')) {
                obj['updated_by'] = ApiClient.convertToType(data['updated_by'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uid
 */
NewDevelopmentalStage.prototype['uid'] = undefined;

/**
 * @member {String} name
 */
NewDevelopmentalStage.prototype['name'] = undefined;

/**
 * @member {Number} begin
 */
NewDevelopmentalStage.prototype['begin'] = undefined;

/**
 * @member {Number} end
 */
NewDevelopmentalStage.prototype['end'] = undefined;

/**
 * @member {Number} order
 */
NewDevelopmentalStage.prototype['order'] = undefined;

/**
 * @member {Array.<Number>} timepoints
 */
NewDevelopmentalStage.prototype['timepoints'] = undefined;

/**
 * @member {Boolean} promoterDB
 */
NewDevelopmentalStage.prototype['promoterDB'] = undefined;

/**
 * @member {Date} published_at
 */
NewDevelopmentalStage.prototype['published_at'] = undefined;

/**
 * @member {String} created_by
 */
NewDevelopmentalStage.prototype['created_by'] = undefined;

/**
 * @member {String} updated_by
 */
NewDevelopmentalStage.prototype['updated_by'] = undefined;






export default NewDevelopmentalStage;

