/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewPromoter model module.
 * @module model/NewPromoter
 * @version 1.0.0
 */
class NewPromoter {
    /**
     * Constructs a new <code>NewPromoter</code>.
     * @alias module:model/NewPromoter
     * @param uid {String} 
     */
    constructor(uid) { 
        
        NewPromoter.initialize(this, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uid) { 
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>NewPromoter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewPromoter} obj Optional instance to populate.
     * @return {module:model/NewPromoter} The populated <code>NewPromoter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewPromoter();

            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('cellsByLineaging')) {
                obj['cellsByLineaging'] = ApiClient.convertToType(data['cellsByLineaging'], ['String']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
            }
            if (data.hasOwnProperty('timepoints')) {
                obj['timepoints'] = ApiClient.convertToType(data['timepoints'], ['Number']);
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('updated_by')) {
                obj['updated_by'] = ApiClient.convertToType(data['updated_by'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uid
 */
NewPromoter.prototype['uid'] = undefined;

/**
 * @member {Array.<String>} cellsByLineaging
 */
NewPromoter.prototype['cellsByLineaging'] = undefined;

/**
 * @member {String} metadata
 */
NewPromoter.prototype['metadata'] = undefined;

/**
 * @member {Array.<Number>} timepoints
 */
NewPromoter.prototype['timepoints'] = undefined;

/**
 * @member {Date} published_at
 */
NewPromoter.prototype['published_at'] = undefined;

/**
 * @member {String} created_by
 */
NewPromoter.prototype['created_by'] = undefined;

/**
 * @member {String} updated_by
 */
NewPromoter.prototype['updated_by'] = undefined;






export default NewPromoter;

