/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewSynapse model module.
 * @module model/NewSynapse
 * @version 1.0.0
 */
class NewSynapse {
    /**
     * Constructs a new <code>NewSynapse</code>.
     * @alias module:model/NewSynapse
     * @param uid {String} 
     */
    constructor(uid) { 
        
        NewSynapse.initialize(this, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uid) { 
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>NewSynapse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewSynapse} obj Optional instance to populate.
     * @return {module:model/NewSynapse} The populated <code>NewSynapse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewSynapse();

            if (data.hasOwnProperty('neuronPre')) {
                obj['neuronPre'] = ApiClient.convertToType(data['neuronPre'], 'String');
            }
            if (data.hasOwnProperty('neuronsPost')) {
                obj['neuronsPost'] = ApiClient.convertToType(data['neuronsPost'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('timepoints')) {
                obj['timepoints'] = ApiClient.convertToType(data['timepoints'], ['Number']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
            }
            if (data.hasOwnProperty('section')) {
                obj['section'] = ApiClient.convertToType(data['section'], 'String');
            }
            if (data.hasOwnProperty('zs')) {
                obj['zs'] = ApiClient.convertToType(data['zs'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('updated_by')) {
                obj['updated_by'] = ApiClient.convertToType(data['updated_by'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} neuronPre
 */
NewSynapse.prototype['neuronPre'] = undefined;

/**
 * @member {Array.<String>} neuronsPost
 */
NewSynapse.prototype['neuronsPost'] = undefined;

/**
 * @member {module:model/NewSynapse.TypeEnum} type
 */
NewSynapse.prototype['type'] = undefined;

/**
 * @member {String} uid
 */
NewSynapse.prototype['uid'] = undefined;

/**
 * @member {Array.<Number>} timepoints
 */
NewSynapse.prototype['timepoints'] = undefined;

/**
 * @member {String} metadata
 */
NewSynapse.prototype['metadata'] = undefined;

/**
 * @member {String} section
 */
NewSynapse.prototype['section'] = undefined;

/**
 * @member {String} zs
 */
NewSynapse.prototype['zs'] = undefined;

/**
 * @member {module:model/NewSynapse.PositionEnum} position
 */
NewSynapse.prototype['position'] = undefined;

/**
 * @member {Date} published_at
 */
NewSynapse.prototype['published_at'] = undefined;

/**
 * @member {String} created_by
 */
NewSynapse.prototype['created_by'] = undefined;

/**
 * @member {String} updated_by
 */
NewSynapse.prototype['updated_by'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
NewSynapse['TypeEnum'] = {

    /**
     * value: "chemical"
     * @const
     */
    "chemical": "chemical",

    /**
     * value: "electrical"
     * @const
     */
    "electrical": "electrical"
};


/**
 * Allowed values for the <code>position</code> property.
 * @enum {String}
 * @readonly
 */
NewSynapse['PositionEnum'] = {

    /**
     * value: "pre"
     * @const
     */
    "pre": "pre",

    /**
     * value: "post"
     * @const
     */
    "post": "post"
};



export default NewSynapse;

