/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewUsersPermissionsUser model module.
 * @module model/NewUsersPermissionsUser
 * @version 1.0.0
 */
class NewUsersPermissionsUser {
    /**
     * Constructs a new <code>NewUsersPermissionsUser</code>.
     * @alias module:model/NewUsersPermissionsUser
     * @param username {String} 
     * @param email {String} 
     */
    constructor(username, email) { 
        
        NewUsersPermissionsUser.initialize(this, username, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, email) { 
        obj['username'] = username;
        obj['email'] = email;
    }

    /**
     * Constructs a <code>NewUsersPermissionsUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewUsersPermissionsUser} obj Optional instance to populate.
     * @return {module:model/NewUsersPermissionsUser} The populated <code>NewUsersPermissionsUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewUsersPermissionsUser();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('resetPasswordToken')) {
                obj['resetPasswordToken'] = ApiClient.convertToType(data['resetPasswordToken'], 'String');
            }
            if (data.hasOwnProperty('confirmationToken')) {
                obj['confirmationToken'] = ApiClient.convertToType(data['confirmationToken'], 'String');
            }
            if (data.hasOwnProperty('confirmed')) {
                obj['confirmed'] = ApiClient.convertToType(data['confirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('blocked')) {
                obj['blocked'] = ApiClient.convertToType(data['blocked'], 'Boolean');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('updated_by')) {
                obj['updated_by'] = ApiClient.convertToType(data['updated_by'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
NewUsersPermissionsUser.prototype['username'] = undefined;

/**
 * @member {String} email
 */
NewUsersPermissionsUser.prototype['email'] = undefined;

/**
 * @member {String} provider
 */
NewUsersPermissionsUser.prototype['provider'] = undefined;

/**
 * @member {String} password
 */
NewUsersPermissionsUser.prototype['password'] = undefined;

/**
 * @member {String} resetPasswordToken
 */
NewUsersPermissionsUser.prototype['resetPasswordToken'] = undefined;

/**
 * @member {String} confirmationToken
 */
NewUsersPermissionsUser.prototype['confirmationToken'] = undefined;

/**
 * @member {Boolean} confirmed
 * @default false
 */
NewUsersPermissionsUser.prototype['confirmed'] = false;

/**
 * @member {Boolean} blocked
 * @default false
 */
NewUsersPermissionsUser.prototype['blocked'] = false;

/**
 * @member {String} role
 */
NewUsersPermissionsUser.prototype['role'] = undefined;

/**
 * @member {String} created_by
 */
NewUsersPermissionsUser.prototype['created_by'] = undefined;

/**
 * @member {String} updated_by
 */
NewUsersPermissionsUser.prototype['updated_by'] = undefined;






export default NewUsersPermissionsUser;

