/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Neuron from './Neuron';

/**
 * The Promoter model module.
 * @module model/Promoter
 * @version 1.0.0
 */
class Promoter {
    /**
     * Constructs a new <code>Promoter</code>.
     * @alias module:model/Promoter
     * @param id {String} 
     */
    constructor(id) { 
        
        Promoter.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Promoter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Promoter} obj Optional instance to populate.
     * @return {module:model/Promoter} The populated <code>Promoter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Promoter();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], ['String']);
            }
            if (data.hasOwnProperty('cellsByLineaging')) {
                obj['cellsByLineaging'] = ApiClient.convertToType(data['cellsByLineaging'], [Neuron]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
            }
            if (data.hasOwnProperty('timepoints')) {
                obj['timepoints'] = ApiClient.convertToType(data['timepoints'], ['Number']);
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Promoter.prototype['id'] = undefined;

/**
 * @member {String} uid
 */
Promoter.prototype['uid'] = undefined;

/**
 * @member {Array.<String>} files
 */
Promoter.prototype['files'] = undefined;

/**
 * @member {Array.<module:model/Neuron>} cellsByLineaging
 */
Promoter.prototype['cellsByLineaging'] = undefined;

/**
 * @member {String} metadata
 */
Promoter.prototype['metadata'] = undefined;

/**
 * @member {Array.<Number>} timepoints
 */
Promoter.prototype['timepoints'] = undefined;

/**
 * @member {Date} published_at
 */
Promoter.prototype['published_at'] = undefined;






export default Promoter;

