/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResetPasswordForm model module.
 * @module model/ResetPasswordForm
 * @version 1.0.0
 */
class ResetPasswordForm {
    /**
     * Constructs a new <code>ResetPasswordForm</code>.
     * @alias module:model/ResetPasswordForm
     * @param code {String} 
     * @param password {String} 
     * @param passwordConfirmation {String} 
     */
    constructor(code, password, passwordConfirmation) { 
        
        ResetPasswordForm.initialize(this, code, password, passwordConfirmation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, password, passwordConfirmation) { 
        obj['code'] = code;
        obj['password'] = password;
        obj['passwordConfirmation'] = passwordConfirmation;
    }

    /**
     * Constructs a <code>ResetPasswordForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResetPasswordForm} obj Optional instance to populate.
     * @return {module:model/ResetPasswordForm} The populated <code>ResetPasswordForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResetPasswordForm();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('passwordConfirmation')) {
                obj['passwordConfirmation'] = ApiClient.convertToType(data['passwordConfirmation'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
ResetPasswordForm.prototype['code'] = undefined;

/**
 * @member {String} password
 */
ResetPasswordForm.prototype['password'] = undefined;

/**
 * @member {String} passwordConfirmation
 */
ResetPasswordForm.prototype['passwordConfirmation'] = undefined;






export default ResetPasswordForm;

