/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UploadForm model module.
 * @module model/UploadForm
 * @version 1.0.0
 */
class UploadForm {
    /**
     * Constructs a new <code>UploadForm</code>.
     * @alias module:model/UploadForm
     * @param files {String} 
     */
    constructor(files) { 
        
        UploadForm.initialize(this, files);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, files) { 
        obj['files'] = files;
    }

    /**
     * Constructs a <code>UploadForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UploadForm} obj Optional instance to populate.
     * @return {module:model/UploadForm} The populated <code>UploadForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadForm();

            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} files
 */
UploadForm.prototype['files'] = undefined;






export default UploadForm;

