/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsRole from './UsersPermissionsRole';

/**
 * The UsersPermissionsUser model module.
 * @module model/UsersPermissionsUser
 * @version 1.0.0
 */
class UsersPermissionsUser {
    /**
     * Constructs a new <code>UsersPermissionsUser</code>.
     * @alias module:model/UsersPermissionsUser
     * @param id {String} 
     * @param username {String} 
     * @param email {String} 
     */
    constructor(id, username, email) { 
        
        UsersPermissionsUser.initialize(this, id, username, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, username, email) { 
        obj['id'] = id;
        obj['username'] = username;
        obj['email'] = email;
    }

    /**
     * Constructs a <code>UsersPermissionsUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsUser} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsUser} The populated <code>UsersPermissionsUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('confirmed')) {
                obj['confirmed'] = ApiClient.convertToType(data['confirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('blocked')) {
                obj['blocked'] = ApiClient.convertToType(data['blocked'], 'Boolean');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = UsersPermissionsRole.constructFromObject(data['role']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UsersPermissionsUser.prototype['id'] = undefined;

/**
 * @member {String} username
 */
UsersPermissionsUser.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UsersPermissionsUser.prototype['email'] = undefined;

/**
 * @member {String} provider
 */
UsersPermissionsUser.prototype['provider'] = undefined;

/**
 * @member {Boolean} confirmed
 * @default false
 */
UsersPermissionsUser.prototype['confirmed'] = false;

/**
 * @member {Boolean} blocked
 * @default false
 */
UsersPermissionsUser.prototype['blocked'] = false;

/**
 * @member {module:model/UsersPermissionsRole} role
 */
UsersPermissionsUser.prototype['role'] = undefined;






export default UsersPermissionsUser;

