/* eslint-disable */
/**
 * NeuroScan
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersPermissionsRole model module.
 * @module model/UsersPermissionsRole
 * @version 1.0.0
 */
class UsersPermissionsRole {
    /**
     * Constructs a new <code>UsersPermissionsRole</code>.
     * @alias module:model/UsersPermissionsRole
     * @param id {String} 
     * @param name {String} 
     */
    constructor(id, name) { 
        
        UsersPermissionsRole.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>UsersPermissionsRole</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsRole} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsRole} The populated <code>UsersPermissionsRole</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsRole();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [Object]);
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UsersPermissionsRole.prototype['id'] = undefined;

/**
 * @member {String} name
 */
UsersPermissionsRole.prototype['name'] = undefined;

/**
 * @member {String} description
 */
UsersPermissionsRole.prototype['description'] = undefined;

/**
 * @member {String} type
 */
UsersPermissionsRole.prototype['type'] = undefined;

/**
 * @member {Array.<Object>} permissions
 */
UsersPermissionsRole.prototype['permissions'] = undefined;

/**
 * @member {Array.<Object>} users
 */
UsersPermissionsRole.prototype['users'] = undefined;






export default UsersPermissionsRole;

