/* eslint-disable */

/**
 * NeuroScan (latest)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Contact from './model/Contact';
import Cphate from './model/Cphate';
import DevelopmentalStage from './model/DevelopmentalStage';
import EmailConfirmationForm from './model/EmailConfirmationForm';
import EmailForm from './model/EmailForm';
import Error from './model/Error';
import ForgotPasswordForm from './model/ForgotPasswordForm';
import LocalAuthForm from './model/LocalAuthForm';
import Neuron from './model/Neuron';
import NewContact from './model/NewContact';
import NewCphate from './model/NewCphate';
import NewDevelopmentalStage from './model/NewDevelopmentalStage';
import NewNeuron from './model/NewNeuron';
import NewPromoter from './model/NewPromoter';
import NewSynapse from './model/NewSynapse';
import NewUsersPermissionsRole from './model/NewUsersPermissionsRole';
import NewUsersPermissionsUser from './model/NewUsersPermissionsUser';
import Promoter from './model/Promoter';
import ResetPasswordForm from './model/ResetPasswordForm';
import Synapse from './model/Synapse';
import UploadForm from './model/UploadForm';
import UsersPermissionsRole from './model/UsersPermissionsRole';
import UsersPermissionsUser from './model/UsersPermissionsUser';
import ContactApi from './api/ContactApi';
import CphateApi from './api/CphateApi';
import DevelopmentalStageApi from './api/DevelopmentalStageApi';
import EmailEmailApi from './api/EmailEmailApi';
import NeuronApi from './api/NeuronApi';
import PromoterApi from './api/PromoterApi';
import SynapseApi from './api/SynapseApi';
import UploadFileApi from './api/UploadFileApi';
import UsersPermissionsRoleApi from './api/UsersPermissionsRoleApi';
import UsersPermissionsUserApi from './api/UsersPermissionsUserApi';

/**
 * JS API client generated by OpenAPI Generator.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var NeuroScanLatest = require('index'); // See note below*.
 * var xxxSvc = new NeuroScanLatest.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new NeuroScanLatest.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new NeuroScanLatest.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new NeuroScanLatest.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 1.0.0
 */
export {
  /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
  ApiClient,

  /**
     * The Contact model constructor.
     * @property {module:model/Contact}
     */
  Contact,

  /**
     * The Cphate model constructor.
     * @property {module:model/Cphate}
     */
  Cphate,

  /**
     * The DevelopmentalStage model constructor.
     * @property {module:model/DevelopmentalStage}
     */
  DevelopmentalStage,

  /**
     * The EmailConfirmationForm model constructor.
     * @property {module:model/EmailConfirmationForm}
     */
  EmailConfirmationForm,

  /**
     * The EmailForm model constructor.
     * @property {module:model/EmailForm}
     */
  EmailForm,

  /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
  Error,

  /**
     * The ForgotPasswordForm model constructor.
     * @property {module:model/ForgotPasswordForm}
     */
  ForgotPasswordForm,

  /**
     * The LocalAuthForm model constructor.
     * @property {module:model/LocalAuthForm}
     */
  LocalAuthForm,

  /**
     * The Neuron model constructor.
     * @property {module:model/Neuron}
     */
  Neuron,

  /**
     * The NewContact model constructor.
     * @property {module:model/NewContact}
     */
  NewContact,

  /**
     * The NewCphate model constructor.
     * @property {module:model/NewCphate}
     */
  NewCphate,

  /**
     * The NewDevelopmentalStage model constructor.
     * @property {module:model/NewDevelopmentalStage}
     */
  NewDevelopmentalStage,

  /**
     * The NewNeuron model constructor.
     * @property {module:model/NewNeuron}
     */
  NewNeuron,

  /**
     * The NewPromoter model constructor.
     * @property {module:model/NewPromoter}
     */
  NewPromoter,

  /**
     * The NewSynapse model constructor.
     * @property {module:model/NewSynapse}
     */
  NewSynapse,

  /**
     * The NewUsersPermissionsRole model constructor.
     * @property {module:model/NewUsersPermissionsRole}
     */
  NewUsersPermissionsRole,

  /**
     * The NewUsersPermissionsUser model constructor.
     * @property {module:model/NewUsersPermissionsUser}
     */
  NewUsersPermissionsUser,

  /**
     * The Promoter model constructor.
     * @property {module:model/Promoter}
     */
  Promoter,

  /**
     * The ResetPasswordForm model constructor.
     * @property {module:model/ResetPasswordForm}
     */
  ResetPasswordForm,

  /**
     * The Synapse model constructor.
     * @property {module:model/Synapse}
     */
  Synapse,

  /**
     * The UploadForm model constructor.
     * @property {module:model/UploadForm}
     */
  UploadForm,

  /**
     * The UsersPermissionsRole model constructor.
     * @property {module:model/UsersPermissionsRole}
     */
  UsersPermissionsRole,

  /**
     * The UsersPermissionsUser model constructor.
     * @property {module:model/UsersPermissionsUser}
     */
  UsersPermissionsUser,

  /**
     * The ContactApi service constructor.
     * @property {module:api/ContactApi}
     */
  ContactApi,

  /**
     * The CphateApi service constructor.
     * @property {module:api/CphateApi}
     */
  CphateApi,

  /**
     * The DevelopmentalStageApi service constructor.
     * @property {module:api/DevelopmentalStageApi}
     */
  DevelopmentalStageApi,

  /**
     * The EmailEmailApi service constructor.
     * @property {module:api/EmailEmailApi}
     */
  EmailEmailApi,

  /**
     * The NeuronApi service constructor.
     * @property {module:api/NeuronApi}
     */
  NeuronApi,

  /**
     * The PromoterApi service constructor.
     * @property {module:api/PromoterApi}
     */
  PromoterApi,

  /**
     * The SynapseApi service constructor.
     * @property {module:api/SynapseApi}
     */
  SynapseApi,

  /**
     * The UploadFileApi service constructor.
     * @property {module:api/UploadFileApi}
     */
  UploadFileApi,

  /**
     * The UsersPermissionsRoleApi service constructor.
     * @property {module:api/UsersPermissionsRoleApi}
     */
  UsersPermissionsRoleApi,

  /**
     * The UsersPermissionsUserApi service constructor.
     * @property {module:api/UsersPermissionsUserApi}
     */
  UsersPermissionsUserApi,
};
