harness:
  subdomain: neuroscan
  secured: false
  service:
    port: 1337
    auto: true
  deployment:
    auto: true
    port: 1337
    volume:
      name: neuroscan-storage
      mountpath: /opt/storage
      size: 20Gi
  # livenessProbe:
  #   path: /api/live
  # readinessProbe:
  #   path: /api/ready
  env:
    - name: DATABASE_FILENAME
      value: /opt/storage/db/data.db
  dependencies:
    build:
      - cloudharness-base
