local: true
tls: false
secured_gatekeepers: false
nameOverride: ''
fullnameOverride: ''
domain: yale.metacell.us
namespace: geppetto-yale
mainapp: frontend
registry:
  name: ''
  secret: ''
tag: latest
apps:
  strapi:
    harness:
      subdomain: api
      domain: yale.metacell.us
      secured: false
      deployment:
        auto: true
        replicas: 1
        image: geppetto-yale-neuro-scan-backend:latest
        name: strapi
        port: 1337
        volume:
          name: storage
          mountpath: /opt/storage
          size: 2Gi
        resources: &id001
          requests:
            memory: 512Mi
            cpu: 10m
          limits:
            memory: 1024Mi
            cpu: 500m
      env:
        - name: DATABASE_FILENAME
          value: /opt/storage/db/data.db
      service:
        auto: true
        name: strapi
        port: 1337
      database:
        auto: false
      use_services: []
      name: strapi
      resource:
    enabled: true
    harvest: true
    image: geppetto-yale-neuro-scan-backend:latest
    name: strapi
    port: 1337
    resources: *id001
  frontend:
    harness:
      subdomain: scan
      domain: yale.metacell.us
      secured: false
      deployment:
        auto: true
        replicas: 1
        image: geppetto-yale-neuro-scan-frontend:latest
        name: frontend
        port: 80
        resources: &id001
          requests:
            memory: 256Mi
            cpu: 10m
          limits:
            memory: 512Mi
            cpu: 100m
      service:
        auto: true
        name: frontend
        port: 80
      database:
        auto: false
      use_services: [ ]
      name: frontend
      resource:
    enabled: true
    harvest: true
    image: geppetto-yale-neuro-scan-frontend:latest
    name: frontend
    port: 80
    resources: *id001
env:
- name: CH_VERSION
  value: 0.0.1
- name: CH_CHART_VERSION
  value: 0.0.1
- name: CH_DOMAIN
  value: yale.metacell.us
- name: CH_IMAGE_REGISTRY
  value: ''
- name: CH_IMAGE_TAG
  value: latest
privenv:
ingress:
  enabled: true
  name: geppetto-yale-ingress
  ssl_redirect: true
  letsencrypt:
    email: filippo@metacell.us
backup:
  active: false
