stages:
  - read_filename_config.json
  - read_xlsx_config.json
  - join_left_0_1
  - read_web_config.json
  - join_left_2_3
  - custom_4_/home/afonso/Projects/MetaCell/geppetto-NeuroSCAN/ingestion/parsers/neurons/custom_script/__init__.py
  - export_5_export_config.json